language: r
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages
compiler: clang

os: 
  - osx
  - linux
  
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libgsl-dev
    - libudunits2-dev
    - libgdal-dev
    - libproj-dev
 
r_github_packages:
  - jimhester/covr

before_install:
 # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
 # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
 # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmagick++-dev; fi
  # GSL, forbidden
  # - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then sudo brew install gsl; fi

after_success:
  - Rscript -e 'library(covr); codecov()'
#  - Rscript -e 'library(goodpractice); gp()'
