# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_ancestry_hmm <- function(sample_matrix, cmd_line_options, num_options, genetic_data, viterbi) {
    .Call('_ancestryhmmR_run_ancestry_hmm', PACKAGE = 'ancestryhmmR', sample_matrix, cmd_line_options, num_options, genetic_data, viterbi)
}

