# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_ancestry_hmm_cpp <- function(sample_matrix, cmd_line_options, genetic_data, viterbi, pulse1, pulse2, ancestry_proportions, use_genome_data) {
    .Call('_ancestryhmmR_run_ancestry_hmm_cpp', PACKAGE = 'ancestryhmmR', sample_matrix, cmd_line_options, genetic_data, viterbi, pulse1, pulse2, ancestry_proportions, use_genome_data)
}

